---
title: "Welcome Page"
---
```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```
Over the semester, each team will pick a business-related Kaggle competition, or the Quantopian competition, to research and critique. On the last day of class, the team will give a 15-minute presentation on their Kaggle research project. The presentation should cover

1. An overview of the Kaggle/Quantopian competition - what's the objective? where does the dataset come from? what are the key features?
2. A brief critique of select Notebooks on this competition available in the public domain - The team should critically evaluate other people's published work using concepts learned from the Machine Learning 1 and Machine Learning 2 coursework.
3. Based on what the team has researched, the team should create their own solution in R to the competition and explain why they believe the solution is the best, and what is new or different from published Notebooks in some conceptually rigorous way based on the Machine Learning 1 and Machine Learning 2 coursework. You must code your solution in R.
4. A brief discussion of reproducibility of your work, or the published Notebooks, based on this Machine Learning Reproducibility Checklist

The team should create a Github page to host their work, including code and presentation.

Grading rubric for this assignment will be available here soon. An external judge may contribute to the scoring of the presentations.

Each team should nominate a captain who will serve as the primary contact person who communicates with the instructor. By the end of Week 2, each team should select a unique Kaggle competition (i.e., no two teams, across the two class sections, can select the same Kaggle competition). There are 11 teams in each class section and 22 teams all together. Topic choices are first come first serve. As soon as the team decides on a competition, the team captain should email the instructor to claim the competition. The instructor will post team topic claims on this webpage here so everyone can see what's available, what's taken, etc. The following is a list of potential topics. Teams are welcome to select a competition not on the list, as long as the topic is approved by the instructor.